# Generated by Django 3.2 on 2022-07-06 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advanced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=150, null=True)),
                ('meta_description', models.TextField(blank=True, max_length=400, null=True)),
                ('password_bio', models.CharField(blank=True, max_length=150, null=True)),
                ('custom_css', models.TextField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_color', models.CharField(blank=True, max_length=150, null=True)),
                ('font', models.CharField(blank=True, max_length=150, null=True)),
                ('text_color', models.CharField(blank=True, max_length=150, null=True)),
                ('btn_color', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contactform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=300, null=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Heading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=300, null=True)),
                ('color', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_aws_class', models.CharField(blank=True, max_length=150, null=True)),
                ('text', models.CharField(blank=True, max_length=150, null=True)),
                ('link', models.CharField(blank=True, max_length=150, null=True)),
                ('color', models.CharField(blank=True, max_length=150, null=True)),
                ('background_color', models.CharField(blank=True, max_length=150, null=True)),
                ('style', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('price', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('link', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sociallinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(blank=True, max_length=220, null=True)),
                ('twitter', models.CharField(blank=True, max_length=220, null=True)),
                ('instagram', models.CharField(blank=True, max_length=220, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=220, null=True)),
                ('youtube', models.CharField(blank=True, max_length=220, null=True)),
                ('telegram', models.CharField(blank=True, max_length=220, null=True)),
                ('pinterest', models.CharField(blank=True, max_length=220, null=True)),
                ('snapchat', models.CharField(blank=True, max_length=220, null=True)),
                ('discourd', models.CharField(blank=True, max_length=220, null=True)),
                ('twitch', models.CharField(blank=True, max_length=220, null=True)),
                ('shopify', models.CharField(blank=True, max_length=220, null=True)),
                ('amazon', models.CharField(blank=True, max_length=220, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='vCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('site', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('state', models.CharField(blank=True, max_length=150, null=True)),
                ('country', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=150, null=True)),
                ('html', models.TextField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('rss_feed', models.CharField(blank=True, max_length=150, null=True)),
                ('news_letter', models.CharField(blank=True, max_length=150, null=True)),
                ('youtube_link', models.CharField(blank=True, max_length=150, null=True)),
                ('apple_music', models.CharField(blank=True, max_length=150, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=150, null=True)),
                ('spotify_link', models.CharField(blank=True, max_length=150, null=True)),
                ('contact_form', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bio.contactform')),
                ('heading', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bio.heading')),
                ('link', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bio.link')),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bio.product')),
                ('vcard', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bio.vcard')),
            ],
        ),
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(blank=True, max_length=150, null=True)),
                ('page_alias', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/bio_img/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advanced', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bio.advanced')),
                ('appearance', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bio.appearance')),
                ('content', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bio.content')),
                ('social_links', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bio.sociallinks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
